"""Inbound auth + per-client rate limiting (Postgres-backed).

Two layers:
  • require_admin — protects /api/* admin routes. Uses a static admin token
    coming from FREEAI_ADMIN_TOKEN or autogenerated in data/admin_token.
  • require_client — protects /v1/* client routes. Looks up the bearer key in
    the clients table and enforces per-client rpm via ClientRateRepository,
    which is backed by the `client_rate_events` table and the plpgsql
    function `freeai_try_reserve_client`. In bootstrap mode (no clients
    exist and FREEAI_REQUIRE_AUTH is false) the route is open.
"""
from __future__ import annotations

import os
import secrets
from typing import Optional

from fastapi import Depends, Header, HTTPException, Request, status
from sqlalchemy.ext.asyncio import AsyncSession

from .db.session import get_session
from .logging_config import get_logger
from .repositories import ClientRateRepository, ClientRepository
from .settings import get_settings

log = get_logger("freeai.security")


# ──────────────── admin token bootstrap ────────────────


def _ensure_admin_token() -> str:
    settings = get_settings()
    if settings.admin_token:
        return settings.admin_token
    if settings.admin_token_path.exists():
        return settings.admin_token_path.read_text(encoding="utf-8").strip()
    settings.admin_token_path.parent.mkdir(parents=True, exist_ok=True)
    token = "adm_" + secrets.token_urlsafe(28)
    settings.admin_token_path.write_text(token, encoding="utf-8")
    try:
        os.chmod(settings.admin_token_path, 0o600)
    except Exception:
        pass
    log.warning(
        "admin_token_generated",
        token=token,
        path=str(settings.admin_token_path),
        message="save this — needed to manage providers/clients",
    )
    return token


ADMIN_TOKEN: Optional[str] = None


def get_admin_token() -> str:
    global ADMIN_TOKEN
    if ADMIN_TOKEN is None:
        ADMIN_TOKEN = _ensure_admin_token()
    return ADMIN_TOKEN


def _extract_bearer(authorization: Optional[str]) -> Optional[str]:
    if not authorization:
        return None
    parts = authorization.split(None, 1)
    if len(parts) != 2 or parts[0].lower() != "bearer":
        return None
    return parts[1].strip()


# ──────────────── FastAPI dependencies ────────────────


async def require_client(
    request: Request,
    authorization: Optional[str] = Header(default=None),
    session: AsyncSession = Depends(get_session),
):
    """Auth dependency for /v1/* — bootstrap-aware.

    Returns the matched Client DTO (or None in bootstrap mode). Raises 401 on
    missing/invalid keys and 429 on client rate limit breach.
    """
    settings = get_settings()
    client_repo = ClientRepository(session)
    has_clients = await client_repo.has_any()
    bootstrap = not has_clients and not settings.require_auth

    raw = _extract_bearer(authorization)

    if bootstrap and not raw:
        return None

    if not raw:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="missing API key (use 'Authorization: Bearer <key>')",
            headers={"WWW-Authenticate": "Bearer"},
        )

    client = await client_repo.find_by_raw_key(raw)
    if not client or not client.enabled:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="invalid API key")

    rate_repo = ClientRateRepository(session)
    granted = await rate_repo.try_acquire(client.key_hash, client.rpm_limit)
    if not granted:
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail=f"client rate limit exceeded ({client.rpm_limit} rpm)",
            headers={"Retry-After": "60"},
        )
    request.state.client = client
    return client


async def require_admin(
    authorization: Optional[str] = Header(default=None),
    x_admin_token: Optional[str] = Header(default=None, alias="X-Admin-Token"),
) -> None:
    raw = _extract_bearer(authorization) or x_admin_token
    if not raw or not secrets.compare_digest(raw, get_admin_token()):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="admin auth required")
